# docker-compose.yml

version: '3.8'

services:
  # Frontend service for the React.js app
  frontend:
    build:
      context: ./client
    ports:
      - '3000:3000'
    depends_on:
      - backend

  # Backend service for the Node.js app
  backend:
    build:
      context: ./server
    ports:
      - '3001:3001'
    environment:
      - DB_URL=mongodb://mongo:27017/tictactense
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
